baseURL = "http://guidapile.pages.dev/"
languageCode = "en-us"
title = "Guida Pile's Listings"
theme = "ticky_tacky_dark"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true

[params]
    favicon = "favicon.ico"
    description = "Guida Pile's House Listings And More."
    images = ["img/header01.jpg", "img/header02.jpg"]
    headername = "Listings"
    #msvalidate = ""
    #googlesiteverification = ""

[Author]
    name = "Guida Pile"
