baseURL = "http://guidapile.pages.dev/"
languageCode = "en-us"
title = "Guida Pile - Listings"
theme = "ticky_tacky_dark"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true

[params]
    favicon = "favicon.ico"
    description = "The demonstration page for the Hugo Ticky Tacky Dark theme."
    images = ["img/header01.jpg", "img/header02.jpg"]
    headername = "Guida Pile - House Listings"
    #msvalidate = ""
    #googlesiteverification = ""

[Author]
    name = "Guida Pile"
    email = "pileguida@gmail.com"
